-- Legacy index script retired. Do not execute this file.
-- Mother uniqueness and beneficiary/assessment lookup indexes are defined in
-- db/migrations/004_create_beneficiary_schema.sql and
-- db/migrations/009_create_clinical_ai_schema.sql.
